// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.2.0

package plan

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type PlanHTTPServer interface {
	CreatePlan(context.Context, *CreatePlanRequest) (*emptypb.Empty, error)
	GetPlan(context.Context, *GetPlanRequest) (*GetPlanReply, error)
}

func RegisterPlanHTTPServer(s *http.Server, srv PlanHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/plan/create", _Plan_CreatePlan0_HTTP_Handler(srv))
	r.POST("/api/v1/plan/get", _Plan_GetPlan0_HTTP_Handler(srv))
}

func _Plan_CreatePlan0_HTTP_Handler(srv PlanHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreatePlanRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.plantoremind.v1.plan.Plan/CreatePlan")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreatePlan(ctx, req.(*CreatePlanRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Plan_GetPlan0_HTTP_Handler(srv PlanHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPlanRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.plantoremind.v1.plan.Plan/GetPlan")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPlan(ctx, req.(*GetPlanRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPlanReply)
		return ctx.Result(200, reply)
	}
}

type PlanHTTPClient interface {
	CreatePlan(ctx context.Context, req *CreatePlanRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetPlan(ctx context.Context, req *GetPlanRequest, opts ...http.CallOption) (rsp *GetPlanReply, err error)
}

type PlanHTTPClientImpl struct {
	cc *http.Client
}

func NewPlanHTTPClient(client *http.Client) PlanHTTPClient {
	return &PlanHTTPClientImpl{client}
}

func (c *PlanHTTPClientImpl) CreatePlan(ctx context.Context, in *CreatePlanRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v1/plan/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.plantoremind.v1.plan.Plan/CreatePlan"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *PlanHTTPClientImpl) GetPlan(ctx context.Context, in *GetPlanRequest, opts ...http.CallOption) (*GetPlanReply, error) {
	var out GetPlanReply
	pattern := "/api/v1/plan/get"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.plantoremind.v1.plan.Plan/GetPlan"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
