// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"plan-to-remind/internal/biz"
	"plan-to-remind/internal/conf"
	"plan-to-remind/internal/pkg/json"
	"plan-to-remind/internal/server"
	"plan-to-remind/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	cronSpecUsecase := biz.NewCronSpecUsecase()
	cronService := service.NewCronService(cronSpecUsecase, logger)
	planUsecase := biz.NewPlanUsecase()
	planService := service.NewPlanService(planUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, cronService, planService, logger)
	grpcServer := server.NewGRPCServer(confServer, cronService, planService, logger)
	parser := json.NewParser()
	timerUsecase, cleanup := biz.NewTimerUsecase(data, logger, parser)
	timerService := service.NewTimerService(logger, timerUsecase)
	cronServer := server.NewCronServer(timerService, logger)
	consumerServer := server.NewConsumerServer(data, parser, logger)
	app := newApp(logger, httpServer, grpcServer, cronServer, consumerServer)
	return app, func() {
		cleanup()
	}, nil
}
