server:
  http:
    addr: 0.0.0.0:8000
    timeout: 3s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 3s
data:
  database:
    driver: mysql
    source: root:1234@tcp(127.0.0.1:3306)/plan-to-remind?charset=utf8&parseTime=True&loc=Local
    username: root
    password: "1234"
    url: 127.0.0.1:3306
    database: plan_to_remind
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  pulsar:
    topic: plan_to_remind
    url: pulsar://127.0.0.1:6650
  email:
    host: smtp.qq.com
    username: XXX
    password: XXX
